import 'package:artifact_shop_phase/Item.dart';

class Items {
  static final items = <Item>[
    Item(
      3,
      "Leather Armor",
      Type.Armor,
      "Equipped Hero has +1 Armor.",
      "leather_armor.jpg",
      Rarity.Basic,
    ),
    Item(
      3,
      "Short Sword",
      Type.Weapon,
      "Equipped Hero has +2 Attack.",
      "short_sword.jpg",
      Rarity.Basic,
    ),
    Item(
      3,
      "Healing Salve",
      Type.Weapon,
      "",
      "",
      Rarity.Basic,
    ),
    Item(
      3,
      "Town Portal Scroll",
      Type.Weapon,
      "",
      "",
      Rarity.Basic,
    ),
    Item(
      3,
      "Traveler's Cloak",
      Type.Accessory,
      "Equipped Hero has +4 Health.",
      "travelers_cloak.jpg",
      Rarity.Basic,
    ),
    Item(
      4,
      "Revtel Signet Ring",
      Type.Accessory,
      "Equipped hero has +4 Health and -3 Bounty.",
      "revtel_signet_ring.jpg",
      Rarity.Uncommon,
    ),
    Item(
      4,
      "Fountain Flask",
      Type.Accessory,
      "",
      "",
      Rarity.Uncommon,
    ),
    Item(
      4,
      "Ristul Emblem",
      Type.Accessory,
      "Equipped Hero has +4 Health and -2 Armor. The unit blocking equipped Hero has -2 Armor.",
      "ristul_emblem.jpg",
      Rarity.Rare,
    ),
    Item(
      5,
      "Stonehall Cloak",
      Type.Accessory,
      "Equipped hero has +4 Health. Modify Stonehall Cloak with \"Equipped hero has +2 Health\" after the combat phase.",
      "stonehall_cloak.jpg",
      Rarity.Common,
    ),
    Item(
      5,
      "Demagicking Maul",
      Type.Accessory,
      "",
      "",
      Rarity.Common,
    ),
    Item(
      5,
      "Potion of Knowledge",
      Type.Accessory,
      "",
      "",
      Rarity.Common,
    ),
    Item(
      6,
      "Barbed Mail",
      Type.Armor,
      "Equipped hero has +1 Armor and +2 Retaliate.",
      "barbed_mail.jpg",
      Rarity.Common,
    ),
    Item(
      6,
      "Phase Boots",
      Type.Accessory,
      "Equipped Hero has +4 Health.",
      "phase_boots.jpg",
      Rarity.Uncommon,
    ),
    Item(
      6,
      "Stonehall Plate",
      Type.Armor,
      "Equipped hero has +1 Armor. Modify Stonehall Plate with \"Equipped hero has +1 Armor\" after the combat phase.",
      "stonehall_plate.jpg",
      Rarity.Common,
    ),
    Item(
      6,
      "Assassins Veil",
      Type.Armor,
      "",
      "",
      Rarity.Common,
    ),
    Item(
      7,
      "Blink Dagger",
      Type.Weapon,
      "Equipped hero has +2 Attack. Active 2: Move equipped hero to another lane.",
      "blink_dagger.jpg",
      Rarity.Uncommon,
    ),
    Item(
      7,
      "Blade of the Vigil",
      Type.Weapon,
      "Equipped hero has +2 Attack and +2 Cleave.",
      "blade_of_the_vigil.jpg",
      Rarity.Common,
    ),
    Item(
      7,
      "Chainmail",
      Type.Armor,
      "Equipped hero has +2 Armor.",
      "chainmail.jpg",
      Rarity.Common,
    ),
    Item(
      7,
      "Fur-lined Mantle",
      Type.Armor,
      "Equipped hero has +8 Health.",
      "fur-lined_mantle.jpg",
      Rarity.Common,
    ),
    Item(
      7,
      "Jasper Daggers",
      Type.Weapon,
      "Equipped hero has +2 Attack and Pierce.",
      "jasper_daggers.jpg",
      Rarity.Uncommon,
    ),
    Item(
      7,
      "Keenfolk Musket",
      Type.Weapon,
      "Equipped hero has +2 Attack.",
      "keenfolk_musket.jpg",
      Rarity.Common,
    ),
    Item(
      8,
      "Poaching Knife",
      Type.Weapon,
      "Equipped hero has +2 Attack. Get 5 gold after an enemy hero dies. Get 1 gold after an enemy creep dies.",
      "poaching_knife.jpg",
      Rarity.Rare,
    ),
    Item(
      8,
      "Shield of Basilius",
      Type.Armor,
      "Equipped Hero has +2 Armor. Equipped Hero's allied neighbors have +1 Armor.",
      "shield_of_basilius.jpg",
      Rarity.Common,
    ),
    Item(
      8,
      "Bracers of Sacrifice",
      Type.Armor,
      "",
      "",
      Rarity.Common,
    ),
    Item(
      9,
      "Golden Ticket",
      Type.Armor,
      "",
      "",
      Rarity.Common,
    ),
    Item(
      9,
      "Rumusque Vestments",
      Type.Armor,
      "",
      "",
      Rarity.Common,
    ),
    Item(
      10,
      "Book of the Dead",
      Type.Accessory,
      "Equipped hero has +4 Health. Add a charge to Book of the Dead after an allied Melee Creep dies.\r\nActive 2: Summon a Zombie for each charge and remove all charges.",
      "book_of_the_dead.jpg",
      Rarity.Common,
    ),
    Item(
      10,
      "Claszureme Hourglass",
      Type.Accessory,
      "Equipped hero has +4 Heatlh.",
      "claszureme_hourglass.jpg",
      Rarity.Uncommon,
    ),
    Item(
      10,
      "Obliterating Orb",
      Type.Consumable,
      "Condemn an improvement.",
      "obliterating_orb.jpg",
      Rarity.Uncommon,
    ),
    Item(
      10,
      "Red Mist Maul",
      Type.Weapon,
      "Equipped Hero has +2 Attack and +5 Siege.",
      "red_mist_maul.jpg",
      Rarity.Common,
    ),
    Item(
      10,
      "Shield of Aquila",
      Type.Weapon,
      "",
      "",
      Rarity.Common,
    ),
    Item(
      12,
      "Ring of Tarrasque",
      Type.Accessory,
      "Equipped hero has +4 Health and +6 Regeneration.",
      "ring_of_tarrasque.jpg",
      Rarity.Common,
    ),
    Item(
      13,
      "Seraphim Shield",
      Type.Armor,
      "Equipped hero has +2 Armor. All units have -2 Attack.",
      "seraphim_shield.jpg",
      Rarity.Rare,
    ),
    Item(
      13,
      "Cloak of Endless Carnage",
      Type.Armor,
      "",
      "",
      Rarity.Rare,
    ),
    Item(
      15,
      "Claymore",
      Type.Armor,
      "",
      "",
      Rarity.Rare,
    ),
    Item(
      15,
      "Hero's Cape",
      Type.Armor,
      "",
      "",
      Rarity.Rare,
    ),
    Item(
      16,
      "Shiva's Guard",
      Type.Armor,
      "",
      "",
      Rarity.Rare,
    ),
    Item(
      19,
      "Helm of the Dominator",
      Type.Armor,
      "Equipped hero has +3 Armor.\r\nActive 2: Get control of an enemy creep.",
      "helm_of_the_dominator.jpg",
      Rarity.Uncommon,
    ),
    Item(
      19,
      "Vesture of the Tyrant",
      Type.Armor,
      "",
      "",
      Rarity.Uncommon,
    ),
    Item(
      19,
      "Wingfall Hammer",
      Type.Armor,
      "",
      "",
      Rarity.Uncommon,
    ),
    Item(
      22,
      "Shop Deed",
      Type.Consumable,
      "Each item in your Secret Shop costs X less gold, where X is equal to its base cost.",
      "shop_deed.jpg",
      Rarity.Rare,
    ),
    Item(
      25,
      "Apotheosis Blade",
      Type.Weapon,
      "Equipped Hero has +8 Attack and +4 Siege. Condemn units equipped hero deals battle damage to.",
      "apotheosis_blade.jpg",
      Rarity.Rare,
    ),
    Item(
      25,
      "Horn of the Alpha",
      Type.Accessory,
      "Equipped hero has +4 Health.",
      "horn_of_the_alpha.jpg",
      Rarity.Rare,
    ),
    Item(
      25,
      "Nyctasha's Guard",
      Type.Accessory,
      "",
      "",
      Rarity.Rare,
    ),
  ];
}
